### ISSUE TITLE
Fix for additional external resources folder is missing in new build framework

### ISSUE THREAD

**Issue by smohadjer** [biotope/build-framework#33]
Hi guys,

We had a fix for this issue in old version of gulp build as you see here:
https://github.com/virtualidentityag/gulp-build-framework/commit/90d1f7744f2497063126730a6f2856f3bc75ff22

Any particular reason that this was removed?

**Comment by smohadjer** [comment]
I have opened a pull request for this fix:

https://github.com/frontend-framework/build-framework/pull/35

**Comment by timomayer** [comment]
as discussed we ll solve that with another strategy (npm dependencies)
